<?php

namespace Bigtree\Logica;

use accesoBDLocal;
use Bigtree\Datos\DerivadorAutomaticoOperaciones as DerivadorAutomaticoOperacionesDB;
use Bigtree\ExcepcionLogica;
use FuncionesPHPLocal;
use Validaciones;

require_once DIR_CLASES_DB . 'cDerivadorAutomaticoOperaciones.db.php';

class DerivadorAutomaticoOperaciones extends DerivadorAutomaticoOperacionesDB {
    use Validaciones;

    /**
     * @inheritDoc
     */
    public function __construct(accesoBDLocal $conexion, int $formato = FMT_ARRAY) {
        parent::__construct($conexion, $formato);
    }

    /**
     * @inheritDoc
     */
    public function __destruct() {
        parent::__destruct();
    }

    /**
     * @return array
     */
    public function getCampos(): array {
        return $this->campos;
    }

    /**
     * @param string $id
     *
     * @return array
     * @throws \Bigtree\ExcepcionLogica
     */
    public function getCampo(string $id): array {
        if (isset($this->campos[$id]))
            return $this->campos[$id];
        throw new ExcepcionLogica('No existe el campo');
    }

    /**
     * @inheritDoc
     */
    public function buscarxCodigo(array $datos, &$resultado, ?int &$numfilas): bool {
        return parent::buscarxCodigo($datos, $resultado, $numfilas);
    }

    /**
     * @inheritDoc
     */
    public function buscarPorDerivador(array $datos, &$resultado, ?int &$numfilas): bool {
        return parent::buscarPorDerivador($datos, $resultado, $numfilas);
    }

    /**
     * @inheritDoc
     */
    public function insertar(array $datos, ?int &$codigoInsertado): bool {
        if (!$this->_validarInsertar($datos))
            return false;
        try {
            $datos['Orden'] = $this->obtenerUltimoOrden($datos) + 1;
        } catch (ExcepcionLogica $e) {
            $this->setError($e->getError());
            return false;
        }

        if (!empty($datos['CampoBD']))
            $datos['CampoElastic'] = $this->campos[$datos['CampoBD']]['CampoElastic'] ?? '';


        self::setearNull($datos);
        return parent::insertar($datos, $codigoInsertado);
    }

    /**
     * @inheritDoc
     */
    public function modificar(array $datos): bool {
        if (!$this->_validarModificar($datos, $datosRegistro))
            return false;

        if (!empty($datos['CampoBD']))
            $datos['CampoElastic'] = $this->campos[$datos['CampoBD']]['CampoElastic'] ?? '';
        self::setearNull($datos);
        return parent::modificar($datos); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $datos
     *
     * @return bool
     */
    public function eliminar(array $datos): bool {
        $datos['Estado'] = ELIMINADO;
        return $this->cambiarEstado($datos);
    }

    /**
     * @inheritDoc
     */
    public function cambiarEstado(array $datos): bool {
        if (!$this->_validarExistencia($datos, $datosRegistro))
            return false;
        self::setearNull($datos);
        return parent::cambiarEstado($datos);
    }

    /**
     * @param $datos
     *
     * @return bool
     */
    public function modificarOrdenCompleto($datos): bool {
        $datosModif['Orden'] = 1;
        self::setearNull($datosModif);
        foreach ($datos['orden'] as $Id) {
            $datosModif['Id'] = $Id;
            if (!parent::modificarOrden($datosModif))
                return false;
            ++$datosModif['Orden'];
        }

        return true;
    }

    /**
     * @inheritDoc
     */
    protected function _validarInsertar(array $datos): bool {
        return $this->_validarDatosVacios($datos);
    }

    /**
     * @inheritDoc
     */
    protected function _validarModificar(array $datos, ?array &$datosRegistro): bool {
        if (!$this->_validarExistencia($datos, $datosRegistro))
            return false;

        return $this->_validarDatosVacios($datos);
    }

    /**
     * @inheritDoc
     */
    protected function _validarDatosVacios(array $datos): bool {
        if (FuncionesPHPLocal::isEmpty($datos['IdDerivador'])) {
            $this->setError(400, 'Debe ingresar un derivador');
            return false;
        }

        if (FuncionesPHPLocal::isEmpty($datos['IdOperacion'])) {
            $this->setError(400, 'Debe seleccionar una operaci&oacute;n');
            return false;
        } elseif (in_array($datos['IdOperacion'], [2,3]) && FuncionesPHPLocal::isEmpty($datos['ValorComparacion'])) {
            $this->setError(400, 'Debe seleccionar un valor contra el cual comparar');
            return false;
        }

        if (FuncionesPHPLocal::isEmpty($datos['CampoBD'])) {
            $this->setError(400, 'Debe seleccionar un campo de evaluaci&oacute;n');
            return false;
        }

        /*if (FuncionesPHPLocal::isEmpty($datos['CampoElastic'])) {
            $this->setError(400, 'Debe seleccionar un campo en base documental');
            return false;
        }*/

        return true;
    }

    /**
     * @inheritDoc
     */
    protected static function setearNull(array &$datos): void {

        if (FuncionesPHPLocal::isEmpty($datos['Estricto']))
            $datos['Estricto'] = 0;

        if (FuncionesPHPLocal::isEmpty($datos['ValorComparacion']))
            $datos['ValorComparacion'] = 'NULL';

        if (FuncionesPHPLocal::isEmpty($datos['CampoBD']))
            $datos['CampoBD'] = 'NULL';

        if (FuncionesPHPLocal::isEmpty($datos['CampoElastic']))
            $datos['CampoElastic'] = 'NULL';

        if (FuncionesPHPLocal::isEmpty($datos['Estado']))
            $datos['Estado'] = ACTIVO;

        $datos['UltimaModificacionFecha'] = $datos['AltaFecha'] = date('Y-m-d H:i:s');
        $datos['UltimaModificacionUsuario'] = $datos['AltaUsuario'] = $_SESSION['usuariocod'];
    }
}